### ISSUE TITLE
problem for me in extraction

### ISSUE THREAD

**Issue by JimBillyGraham** [justinelliotmeyers/INDIA_ATLAS#1]
Dear Justin,
 Happy to get the data from you.
 Today I Just downloaded the data. everything is working except villages
In extracting the Village DBF the same problem 
![India_VillagesDBF](https://user-images.githubusercontent.com/48754930/82301044-53215a80-99d5-11ea-8d92-3dd3fcdd8277.png)
 kindly do the needful

**Comment by justinelliotmeyers** [comment]
![step1](https://user-images.githubusercontent.com/5324316/82320966-230c9400-99a2-11ea-934f-61717c96511c.png)
only select .zip files, then select extract here.
![step2](https://user-images.githubusercontent.com/5324316/82321002-30c21980-99a2-11ea-8305-cec669188f2c.png)


If you still cannot get it to work, send me your email and i will compress in one larger file.

Have a great day.

**Comment by JimBillyGraham** [comment]
Dear Justin,
 I was doing as you have mentioned. Today also i tried, same error.

**Comment by JimBillyGraham** [comment]
Dear Justin,
 Can you provide the Data for Village points 
![India_VillagesDBF](https://user-images.githubusercontent.com/48754930/82644487-03d66680-9c2f-11ea-9cea-7efe61c9b2cd.png)
