### ISSUE TITLE
Bug in SOI point village

### ISSUE THREAD

**Issue by jranajnu** [justinelliotmeyers/INDIA_ATLAS#4]
Hi Justin

Thanks for keeping the India's shapefile open access. I was trying to open the downloading the file of SOI point village. The file is not opening. I guess the DBF file has a bug. Could you please tell me how to resolve the issue? Many thanks.

**Comment by justinelliotmeyers** [comment]
only extract the villages_2019.dbf.zip with winrar the software will understand to grab the two other files and build the full correct dbf. Enjoy ;)

**Comment by jranajnu** [comment]
Thanks for your prompt reply. I was trying to open the file. It was showing some errors. Kindly see the attached file.

[Bug.docx](https://github.com/justinelliotmeyers/INDIA_ATLAS/files/8281240/Bug.docx)
